services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    init: true  # Add this line
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
        - ./:/var/www
    networks:
      - bookstore-network
  db:
    image: mysql:8.0
    container_name: bookstore-db
    init: true  # Add this line
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
        - ./.docker/mysql/dbdata:/var/lib/mysql
    networks:
      - bookstore-network
  nginx:
    image: nginx:alpine
    container_name: bookstore-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bookstore-network

networks:
  bookstore-network:
    driver: bridge